### ISSUE TITLE
Temporal Convolution Network (TCN) 

### ISSUE THREAD

**Issue by neon5d** [koba-jon/pytorch_cpp#20]
I checked your examples but I still cannot figure out how to build TCN using Pytorch C++.
Can you give me guidance?
or It would be great if the TCN example is added.
Thank you

**Comment by koba-jon** [comment]
TCN is not implemented in this repository.
I plan to add it in the future, and I don't know when it will be.
Thank you!

**Comment by neon5d** [comment]
Thank you for your quick reply and your consideration.
It would be a great help to see the example soon.
Thank you,
